name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests again'
        required: true
jobs:
  build:

    runs-on:  windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
          submodules: true      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: add source to nuget 
      run: dotnet nuget add source "https://nuget.pkg.github.com/YkeSmit1/index.json" --name "githubfeed" --username "YkeSmit1" --password "${{ secrets.GITHUB_TOKEN }}"     
    - name: Install dependencies
      run: dotnet restore
    - name: NuGet Restore
      run: nuget restore Tosr.sln
    - name: Restore from cache and install vcpkg
      # Download and build vcpkg, without installing any port. If content is cached already, it is a no-op.
      uses: lukka/run-vcpkg@v11
    # Now that vcpkg is installed, it is being used to run with desired arguments.
    - name: Install SQLiteCpp using vcpg      
      run: |
        $VCPKG_ROOT/vcpkg install SQLiteCpp:x64-windows
        $VCPKG_ROOT/vcpkg integrate install
      shell: bash      
    - name: Build
      run: msbuild /t:Build /p:Configuration=Release -m Tosr.sln
    - name: Run c# Test
      run: dotnet test --no-restore --configuration Release --verbosity normal .\TosrGui.Test\TosrGui.Test.csproj
    - name: Run c++ Test
      run: .\x64\Release\EngineTest.exe
    - name: Run Integration Test
      run: dotnet test --no-restore --configuration Release --verbosity normal .\TosrIntegration.Test\TosrIntegration.Test.csproj
    - uses: actions/upload-artifact@v4
      with:
        name: distribute
        path: .\Wpf.Tosr\bin\Release\net8.0-windows\
