name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on:  windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0       
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Installing vcpkg (windows)
      run: |
        cd ..
        git clone https://github.com/Microsoft/vcpkg.git
        cd vcpkg
        git checkout
        .\bootstrap-vcpkg.bat
        .\vcpkg.exe install SQLiteCpp:x64-windows
        .\vcpkg.exe install sqlite_orm:x64-windows
    - name: Build
      run: msbuild -/t:Build /p:Configuration=Release Tosr.sln
    - name: Test
      run: dotnet test --no-restore --verbosity normal
